name: final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  pdf: ^3.13.0
  printing: ^5.15.0
  supabase_flutter: ^2.17.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/background.png
    - assets/logo.png
  
  fonts:
    - family: Thmanyah
      fonts:
        - asset: assets/fonts/thmanyahsans-Light.otf
          weight: 300

        - asset: assets/fonts/thmanyahsans-Regular.otf
          weight: 400

        - asset: assets/fonts/thmanyahsans-Medium.otf
          weight: 500

        - asset: assets/fonts/thmanyahsans-Bold.otf
          weight: 700

        - asset: assets/fonts/thmanyahsans-Black.otf
          weight: 900
