name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/WhatsApp Video 2026-09-13 at 12.23.00.webm
    
