name: Build Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Commit web build
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -f build/web
          git diff --cached --quiet || git commit -m "Update Flutter web build"
          git push